### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by mvalbuquerque** [artrmz/siri-shortcuts-demo#1]
I would like to thank you and congratulate you on your article. But when trying to run your source code on iPhone see what happens.
Tks.

<img width="497" alt="captura de tela 2018-11-17 as 18 10 52" src="https://user-images.githubusercontent.com/14190112/48665375-37618f00-ea94-11e8-98b1-357047eb6a21.png">

**Comment by artur-ios-dev** [comment]
Hey, it's because you try to run it on the device, you have to configure your own provisioning to do that. It should run fine on the simulator.
